# packages installed by anaconda's r-essential install
install.packages("ggplot2")
install.packages("plyr")
install.packages("reshape2")
install.packages("dplyr")
install.packages("tidyr")
install.packages("caret")
install.packages("randomforest")
install.packages("data")
install.packages("quantmod")
install.packages("shiny")
install.packages("rmarkdown")
install.packages("glmnet")
install.packages("jsonlite")
install.packages("zoo")
install.packages("irkernel")
install.packages("rbokeh")
install.packages("formatr")
install.packages("tebook")
install.packages("tidyverse")
install.packages("dbi")
install.packages("broom")
install.packages("forcats")
install.packages("haven")
install.packages("hms")
install.packages("httr")
install.packages("lubridate")
install.packages("magrittr")
install.packages("modelr")
install.packages("purrr")
install.packages("readr")
install.packages("readxl")
install.packages("rvest")
install.packages("stringr")
install.packages("tibble")
install.packages("xml2")

# additional packages
install.packages("tinytex")
install.packages("bit")
install.packages("bit64")
install.packages("blob")
install.packages("openssl")
install.packages("keyring")
install.packages("odbc")
install.packages("devtools")


packrat::snapshot()
